FROM microsoft/aspnetcore-build

COPY . /usr/src/server-app
WORKDIR /usr/src/server-app

RUN dotnet restore

CMD dotnet test WebApplication.tests/WebApplication.tests.csproj && rm -rf $(pwd)/publish/* && dotnet publish WebApplication -c Release -o $(pwd)/publish