# -*- mode: ruby -*-
# # vi: set ft=ruby :
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require JSON module
require 'json'

# Read JSON file with box details
nodes = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'nodes.json')))

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Iterate through entries in JSON file
    nodes.each do |node|
        config.vm.define node['name'] do |nodeConfig|
            nodeConfig.vm.box = node['box']
            nodeConfig.vm.hostname = node['name']
            
            nodeConfig.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

            nodeConfig.vm.network :private_network, ip: node['ip']

            if node['name'] == 'jenkins.vm'
                # Expose the VM externally
                nodeConfig.vm.network :forwarded_port, guest: 8080, host: 1234

                # Shared folder for Jenkins VM config
                nodeConfig.vm.synced_folder ".", "/vagrant", disabled: true
                nodeConfig.vm.synced_folder "../jenkins/config/", "/jenkins-config"

                # Provision docker
                nodeConfig.vm.provision "docker", images: ["node", "microsoft/aspnetcore", "microsoft/aspnetcore-build"]
            end

            nodeConfig.vm.provider "virtualbox" do |vb|
                vb.name = node['name']
                vb.memory = node['ram']
            end

                    # Provisioning via bootstrap script
            nodeConfig.vm.provision :shell, :path => node['bootstrap']
        end # config.vm
    end # nodes.each
end # Vagrant.configure