# -*- mode: ruby -*-
# # vi: set ft=ruby :
 
# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/xenial64"

    # Disable the SSH port enabled by default
    config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

    config.vm.define "jenkins.vm" do |jenkins|
        jenkins.vm.hostname = "jenkins.vm"

        # Expose the VM externally
        jenkins.vm.network "forwarded_port", guest: 22, host: 5022
        jenkins.vm.network "forwarded_port", guest: 8080, host: 1234

        # Shared folder for Jenkins VM config
        jenkins.vm.synced_folder ".", "/vagrant", disabled: true
        jenkins.vm.synced_folder "../jenkins/config/", "/jenkins-config"
        
        # VirtualBox configuration
        jenkins.vm.provider "virtualbox" do |vb|
            vb.name = "jenkins.vm"
            vb.memory = 1024
        end

        # Provisioning via bootstrap script
        jenkins.vm.provision "shell", path: "bootstrap-jenkins.sh"
    end
end