FROM node

COPY . /usr/src/client-app
WORKDIR /usr/src/client-app

ENV PORT=80
ENV EXTERNAL_API=http://server-app/api
ENV NODE_ENV=production

EXPOSE 80

RUN npm install
RUN npm run build

CMD npm start