node {
    stage("Checkout") {
        git url: 'https://github.com/matthew-r-richards/continuous-deployment.git'
    }
    stage("Build, Test and Publish Server App") {
        sh 'cd apps/Server; docker run --rm -v $(pwd):/sln --workdir /sln microsoft/aspnetcore-build sh ./build.sh;'
    }
}