node {
    stage("Checkout") {
        git url: 'https://github.com/matthew-r-richards/continuous-deployment.git'
    }
    stage("Build Server App") {
        sh 'cd apps/Server; dotnet restore; dotnet build WebApplication'
    }
}