version: '2'
services:
  server-app:
    container_name: server-app
    build:
      context: ./Server
      dockerfile: Dockerfile-deploy
    image: server-app
    ports:
  client-app:
    container_name: client-app
    build:
      context: ./Client
      dockerfile: Dockerfile-deploy
    image: client-app
    ports:
      - 80:80
